/* tslint:disable */
/* eslint-disable */
/**
 * Example.com
 * This is an **example** API to demonstrate features of the OpenAPI specification. # Introduction This API definition is intended to to be a good starting point for describing your API in [OpenAPI/Swagger format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md). It also demonstrates features of the [create-openapi-repo](https://github.com/Redocly/create-openapi-repo) tool and the [Redoc](https://github.com/Redocly/Redoc) documentation engine. Beyond the standard OpenAPI syntax, we use a few  [vendor extensions](https://github.com/Redocly/Redoc/blob/master/docs/redoc-vendor-extensions.md). # OpenAPI Specification The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can  understand and interact with the remote service with a minimal amount of implementation logic. Similar to what interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service. 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: contact@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Problem,
  Schema,
} from '../models/index';
import {
    ProblemFromJSON,
    ProblemToJSON,
    SchemaFromJSON,
    SchemaToJSON,
} from '../models/index';

export interface OperationIdRequest {
    schema: Omit<Schema, 'readOnlyStringProperty'>;
}

export interface PostPathItemWithExamplesRequest {
    schema: Omit<Schema, 'readOnlyStringProperty'>;
}

/**
 * 
 */
export class TagApi extends runtime.BaseAPI {

    /**
     * Operation description **Markdown**. 
     * Operation summary
     */
    private async operationIdRaw(requestParameters: OperationIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Schema>> {
        if (requestParameters['schema'] == null) {
            throw new runtime.RequiredError(
                'schema',
                'Required parameter "schema" was null or undefined when calling operationId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api_key"] = await this.configuration.apiKey("api_key"); // api_key authentication
        }


        let urlPath = `/pathItem`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchemaToJSON(requestParameters['schema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaFromJSON(jsonValue));
    }

    /**
     * Operation description **Markdown**. 
     * Operation summary
     */
    async operationId(schema: Schema, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Schema> {
        const response = await this.operationIdRaw({ schema: schema }, initOverrides);
        return await response.value();
    }

    /**
     * Operation description **markdown**. 
     * Operation summary with examples
     */
    private async postPathItemWithExamplesRaw(requestParameters: PostPathItemWithExamplesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Schema>> {
        if (requestParameters['schema'] == null) {
            throw new runtime.RequiredError(
                'schema',
                'Required parameter "schema" was null or undefined when calling postPathItemWithExamples().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api_key"] = await this.configuration.apiKey("api_key"); // api_key authentication
        }


        let urlPath = `/pathItemWithExamples`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SchemaToJSON(requestParameters['schema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaFromJSON(jsonValue));
    }

    /**
     * Operation description **markdown**. 
     * Operation summary with examples
     */
    async postPathItemWithExamples(schema: Schema, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Schema> {
        const response = await this.postPathItemWithExamplesRaw({ schema: schema }, initOverrides);
        return await response.value();
    }

}
